name: Test K8s Runner
on: [push]

jobs:
  test:
    runs-on: gh-runners-scale-set # This makes it use your k8s runner
    steps:
      - run: |
          echo "Hello from Kubernetes!"
          echo "Running on pod: $(hostname)"
          kubectl get nodes  # Verify cluster access
